version: '3.8'

services:
  chrono:
    image: "chrono"
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - 3000:5000
    env_file:
      - .env

  mongo:
    image: "mongo"
    restart: on-failure
    env_file:
      - .env.db
